export enum Phase {
    DEFAULT = 'DEFAULT',
    TOUR_REGISTRATION = 'TOUR_REGISTRATION',
    RAT_SERIA_VOTING = 'RAT_SERIA_VOTING',
    RAT_TOUR_VOTING = 'RAT_SERIA_VOTING',
    TEAM_VOTING = 'TEAM_VOTING',
}