import {UserType} from "../models/userType";
import {User} from "../models/user";


export const unregUsers = [
    {nickname: "Малинити", telegramName: "@grubaya"},
    {nickname: "Певица", telegramName: "https://t.me/sdaria_s"},
    {nickname: "Логика", telegramName: "@veizgeim"},
    {nickname: "Тони", telegramName: "https://t.me/gn_t0ny"},
    {nickname: "Космічна", telegramName: "mary_kos"},
    {nickname: "Архи", telegramName: "@vadimmigalenko"},
    {nickname: "Кайфат", telegramName: "@spleanin"},
    {nickname: "Сокрушитель", telegramName: "@mit_zag"},
    {nickname: "f5", telegramName: "T.me/armasher"},
    {nickname: "Leklerk", telegramName: "@Leklerk_k"},
    {nickname: "Грильяж", telegramName: "@grilllage"},
    {nickname: "Марта", telegramName: "https://t.me/mrs_marta"},
    {nickname: "Крис", telegramName: "baranovskayanastya"},
    {nickname: "Аврора", telegramName: "@aurosha"},
    {nickname: "Инженер", telegramName: "https://t.me/andrey_teslya"},
    {nickname: "Комар", telegramName: "@Smurfkomar"},
    {nickname: "Sirius", telegramName: "@aldoshyn"},
    {nickname: "Жирафа", telegramName: "@stmargarita"},
    {nickname: "Miracle", telegramName: "Miracleprg"},
    {nickname: "Абрам", telegramName: "@Mikhrutka"},
    {nickname: "Кукла", telegramName: "Kyklamarina"},
    {nickname: "Адлер", telegramName: "@adler_ua"},
    {nickname: "Шахматист", telegramName: "@platonich3"},
    {nickname: "Tommy", telegramName: "oldangrypirate"},
    {nickname: "filister", telegramName: "@F1l1STER"},
    {nickname: "Харюк", telegramName: "@ArturSayakhov"},
    {nickname: "walle", telegramName: "@nikita_pitalenko"},
    {nickname: "Блукач", telegramName: "@yurivynnyk"},
    {nickname: "Red", telegramName: "@chibirenny"},
    {nickname: "Негрони", telegramName: "@nazar_stt"},
    {nickname: "Сайфер", telegramName: "@XXRater"},
    {nickname: "Moriarty", telegramName: "t.me/maksimiliansm"},
    {nickname: "Бембі", telegramName: "Bembiiii"},
    {nickname: "Snoopy:)", telegramName: "snoopy_ua"},
    {nickname: "Vёska", telegramName: "@pla2visi"},
    {nickname: "Sashko", telegramName: "@alexandrkats"},
    {nickname: "Утка", telegramName: "https://t.me/danya6389"},
    {nickname: "Frodo", telegramName: "Dihubi"},
    {nickname: "Такт", telegramName: "agych"},
    {nickname: "Alisa", telegramName: "@hannaklo"},
    {nickname: "dysheboy", telegramName: "@dysheboy"},
    {nickname: "Дежавю", telegramName: "@mellesacha"},
    {nickname: "Мілка", telegramName: "@lunarMilka"},
    {nickname: "Graf", telegramName: "Lshbbnk"},
    {nickname: "Nikita", telegramName: "@gn_nikita"},
    {nickname: "Deidara", telegramName: "@Vlad_Deid"},
    {nickname: "hds", telegramName: "@vladisback"},
    {nickname: "Дари", telegramName: "@dariazhadanova"},
    {nickname: "Мейзікін", telegramName: "@la_meizikin"},
    {nickname: "DiElectric", telegramName: "@Dmitry_Gibert"},
]

export const unregUserMap: Map<string, User> = new Map([
    ["Малинити", {nickname: "Малинити", telegramName: "@grubaya", chatId: -1, userType: UserType.Default}],
    ["Певица", {nickname: "Певица", telegramName: "https://t.me/sdaria_s", chatId: -1, userType: UserType.Default}],
    ["Логика", {nickname: "Логика", telegramName: "@veizgeim", chatId: -1, userType: UserType.Default}],
    ["Тони", {nickname: "Тони", telegramName: "https://t.me/gn_t0ny", chatId: -1, userType: UserType.Default}],
    ["Космічна", {nickname: "Космічна", telegramName: "mary_kos", chatId: -1, userType: UserType.Default}],
    ["Архи", {nickname: "Архи", telegramName: "@vadimmigalenko", chatId: -1, userType: UserType.Default}],
    ["Кайфат", {nickname: "Кайфат", telegramName: "@spleanin", chatId: -1, userType: UserType.Default}],
    ["Сокрушитель", {nickname: "Сокрушитель", telegramName: "@mit_zag", chatId: -1, userType: UserType.Default}],
    ["f5", {nickname: "f5", telegramName: "T.me/armasher", chatId: -1, userType: UserType.Default}],
    ["Leklerk", {nickname: "Leklerk", telegramName: "@Leklerk_k", chatId: -1, userType: UserType.Default}],
    ["Грильяж", {nickname: "Грильяж", telegramName: "@grilllage", chatId: -1, userType: UserType.Default}],
    ["Марта", {nickname: "Марта", telegramName: "https://t.me/mrs_marta", chatId: -1, userType: UserType.Default}],
    ["Крис", {nickname: "Крис", telegramName: "baranovskayanastya", chatId: -1, userType: UserType.Default}],
    ["Аврора", {nickname: "Аврора", telegramName: "@aurosha", chatId: -1, userType: UserType.Default}],
    ["Инженер", {nickname: "Инженер", telegramName: "https://t.me/andrey_teslya", chatId: -1, userType: UserType.Default}],
    ["Комар", {nickname: "Комар", telegramName: "@Smurfkomar", chatId: -1, userType: UserType.Default}],
    ["Sirius", {nickname: "Sirius", telegramName: "@aldoshyn", chatId: -1, userType: UserType.Default}],
    ["Жирафа", {nickname: "Жирафа", telegramName: "@stmargarita", chatId: -1, userType: UserType.Default}],
    ["Miracle", {nickname: "Miracle", telegramName: "Miracleprg", chatId: -1, userType: UserType.Default}],
    ["Абрам", {nickname: "Абрам", telegramName: "@Mikhrutka", chatId: -1, userType: UserType.Default}],
    ["Кукла", {nickname: "Кукла", telegramName: "Kyklamarina", chatId: -1, userType: UserType.Default}],
    ["Адлер", {nickname: "Адлер", telegramName: "@adler_ua", chatId: -1, userType: UserType.Default}],
    ["Шахматист", {nickname: "Шахматист", telegramName: "@platonich3", chatId: -1, userType: UserType.Default}],
    ["Tommy", {nickname: "Tommy", telegramName: "oldangrypirate", chatId: -1, userType: UserType.Default}],
    ["filister", {nickname: "filister", telegramName: "@F1l1STER", chatId: -1, userType: UserType.Default}],
    ["Харюк", {nickname: "Харюк", telegramName: "@ArturSayakhov", chatId: -1, userType: UserType.Default}],
    ["walle", {nickname: "walle", telegramName: "@nikita_pitalenko", chatId: -1, userType: UserType.Default}],
    ["Блукач", {nickname: "Блукач", telegramName: "@yurivynnyk", chatId: -1, userType: UserType.Default}],
    ["Red", {nickname: "Red", telegramName: "@chibirenny", chatId: -1, userType: UserType.Default}],
    ["Негрони", {nickname: "Негрони", telegramName: "@nazar_stt", chatId: -1, userType: UserType.Default}],
    ["Сайфер", {nickname: "Сайфер", telegramName: "@XXRater", chatId: -1, userType: UserType.Default}],
    ["Moriarty", {nickname: "Moriarty", telegramName: "t.me/maksimiliansm", chatId: -1, userType: UserType.Default}],
    ["Бембі", {nickname: "Бембі", telegramName: "Bembiiii", chatId: -1, userType: UserType.Default}],
    ["Snoopy:)", {nickname: "Snoopy:)", telegramName: "snoopy_ua", chatId: -1, userType: UserType.Default}],
    ["Vёska", {nickname: "Vёska", telegramName: "@pla2visi", chatId: -1, userType: UserType.Default}],
    ["Sashko", {nickname: "Sashko", telegramName: "@alexandrkats", chatId: -1, userType: UserType.Default}],
    ["Утка", {nickname: "Утка", telegramName: "https://t.me/danya6389", chatId: -1, userType: UserType.Default}],
    ["Frodo", {nickname: "Frodo", telegramName: "Dihubi", chatId: -1, userType: UserType.Default}],
    ["Такт", {nickname: "Такт", telegramName: "agych", chatId: -1, userType: UserType.Default}],
    ["Alisa", {nickname: "Alisa", telegramName: "@hannaklo", chatId: -1, userType: UserType.Default}],
    ["dysheboy", {nickname: "dysheboy", telegramName: "@dysheboy", chatId: -1, userType: UserType.Default}],
    ["Дежавю", {nickname: "Дежавю", telegramName: "@mellesacha", chatId: -1, userType: UserType.Default}],
    ["Мілка", {nickname: "Мілка", telegramName: "@lunarMilka", chatId: -1, userType: UserType.Default}],
    ["Graf", {nickname: "Graf", telegramName: "Lshbbnk", chatId: -1, userType: UserType.Default}],
    ["Nikita", {nickname: "Nikita", telegramName: "@gn_nikita", chatId: -1, userType: UserType.Default}],
    ["Deidara", {nickname: "Deidara", telegramName: "@Vlad_Deid", chatId: -1, userType: UserType.Default}],
    ["hds", {nickname: "hds", telegramName: "@vladisback", chatId: -1, userType: UserType.Default}],
    ["Дари", {nickname: "Дари", telegramName: "@dariazhadanova", chatId: -1, userType: UserType.Default}],
    ["Мейзікін", {nickname: "Мейзікін", telegramName: "@la_meizikin", chatId: -1, userType: UserType.Default}],
    ["DiElectric", {nickname: "DiElectric", telegramName: "@Dmitry_Gibert", chatId: -1, userType: UserType.Default}]
]);
