import { LocalUserRepository } from "../repositories/userRepository";
import { LocalPlayerRepository } from "../repositories/playerRepository";
import { Telegraf } from "telegraf";
import { TELEGRAM_BOT_TOKEN } from "../config/tokens";
import { UserManager } from "../handlers/registerUser";
import { PlayerManager } from "../handlers/playerManager";
import { NotificationManager } from "../handlers/notificationManager";
import {ViewerManager} from "../handlers/viewerManager";
import {LocalViewerRepository} from "../repositories/viewerRepository";
import {DBManager} from "../utils/dbManager";
import {DBUserRepository} from "../repositories/DBUserRepository";
import {DBPlayerRepository} from "../repositories/DBPlayerRepository";
import {AdminManager} from "../handlers/adminManager";
import {SeriesDB} from "../utils/seriesDB";

export const bot = new Telegraf(TELEGRAM_BOT_TOKEN);
export const userRepository = new DBUserRepository();
export const playerRepository = new DBPlayerRepository();
export const viewerRepository = new LocalViewerRepository();
export const playerManager = new PlayerManager(playerRepository, bot);
export const userManager = new UserManager(bot);
export const viewerManager = new ViewerManager(viewerRepository, bot);
export const notificationManager = new NotificationManager(userRepository, playerRepository, bot);
export const dbManager = new DBManager();
export const dbUserRepository = new DBUserRepository();
export const adminManager = new AdminManager(bot);
export const seriesDB = new SeriesDB();
