import { LocalUserRepository } from "../repositories/userRepository";
import { LocalPlayerRepository } from "../repositories/playerRepository";
import { Telegraf } from "telegraf";
import { TELEGRAM_BOT_TOKEN } from "../config/tokens";
import { UserManager } from "../handlers/registerUser";
import { PlayerManager } from "../handlers/playerManager";
import { NotificationManager } from "../handlers/notificationManager";
import {ViewerManager} from "../handlers/viewerManager";
import {LocalViewerRepository} from "../repositories/viewerRepository";
import {DBManager} from "../utils/dbManager";
import {DBUserRepository} from "../repositories/DBUserRepository";
import {DBPlayerRepository} from "../repositories/DBPlayerRepository";
import {AdminManager} from "../handlers/adminManager";
import {SeriesDB} from "../utils/seriesDB";
import {VoteManager} from "../handlers/voting/voteManager";
import {DBSeriesRepository} from "../repositories/series/DBSeriesRepository";
import {ViewerDB} from "../utils/viewerDB";
import {TeamDB} from "../utils/teamDB";
import {DBTeamRepository} from "../repositories/team/DBTeamRepository";
import {PhaseDB} from "../utils/phaseDB";
import {DBPhaseRepository} from "../repositories/DBPhaseRepository";

export const bot = new Telegraf(TELEGRAM_BOT_TOKEN);
export const userRepository = new DBUserRepository();
export const playerRepository = new DBPlayerRepository();
export const viewerRepository = new LocalViewerRepository();
export const playerManager = new PlayerManager(playerRepository, bot);
export const userManager = new UserManager(bot);
export const viewerManager = new ViewerManager(viewerRepository, bot);
export const voteManager = new VoteManager(viewerRepository, bot);
export const notificationManager = new NotificationManager(userRepository, playerRepository, bot);
export const dbManager = new DBManager();
export const adminManager = new AdminManager(bot);
export const seriesDB = new SeriesDB();
export const seriesRepository= new DBSeriesRepository();
export const viewerDB = new ViewerDB();
export const teamDB = new TeamDB();
export const teamRepository= new DBTeamRepository();
export const phaseDB = new PhaseDB();
export const phaseRepository= new DBPhaseRepository();